### ISSUE TITLE
Could not generate a code: unknown error 

### ISSUE THREAD

**Issue by eggithub** [ChristophWurst/twofactor_admin#110]
Issue regarding generation of codes.
When I fill in a user I get the error: Could not generate a code: unknown error 

This is the info I can give now, if you need more logs let me know.

Nextcloud log tells:

[index] Error: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_twofactor_admin_codes` (`user_id`, `code`, `expires`) VALUES(?, ?, ?)' with params ["*** REMOVED ***", "190884", 1585232958]:

SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... e", Doctrine\DBAL\Dr ... ]})
 1. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... e")
 2. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1063
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "INSERT INTO `oc ... )", {1: "*** REMOVED ***",2: "190884",3: 1585232958})
 3. /var/www/nextcloud/lib/private/DB/Connection.php line 220
    Doctrine\DBAL\Connection->executeUpdate("INSERT INTO `oc ... )", ["*** REMOVED ***","190884",1585232958], [2,2,2])
 4. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 203
    OC\DB\Connection->executeUpdate("INSERT INTO `oc ... )", {dcValue1: "*** REMOVED *** ... 8}, {dcValue1: 2,dcValue2: 2,dcValue3: 2})
 5. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 215
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 126
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/nextcloud/apps/twofactor_admin/lib/Service/CodeStorage.php line 71
    OCP\AppFramework\Db\QBMapper->insert(OCA\TwoFactorAdmin\Db\Code {id: null})
 8. /var/www/nextcloud/apps/twofactor_admin/lib/Controller/AdminCodeController.php line 96
    OCA\TwoFactorAdmin\Service\CodeStorage->generateCode(OC\User\User {})
 9. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\TwoFactorAdmin\Controller\AdminCodeController->create("*** REMOVED ***")
10. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\TwoFactorAdm ... {}, "create")
11. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\TwoFactorAdm ... {}, "create")
12. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\TwoFactorA ... r", "create", OC\AppFramework\ ... {}, {_route: "twofac ... "})
13. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "twofac ... "})
14. /var/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "twofac ... "})
15. /var/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/twofactor_admin/api/admin/code")
16. /var/www/nextcloud/index.php line 38
    OC::handleRequest()

POST /nextcloud/index.php/apps/twofactor_admin/api/admin/code

**Comment by ChristophWurst** [comment]
version of nextcloud and this app?

**Comment by ChristophWurst** [comment]
also please check the table definition in your DB.

**Comment by eggithub** [comment]
NC: 18.0.2/3
Two-Factor Admin Support: 2.0.0

I have another NC instance where this works just ok btw, same versions other platform. Sot this issue might be a local problem, when I come to think of it.

check the table definition? What am I looking for?

Is it possible to perhaps, remove the app, clean the database (with occ or something) and reinstall?

**Comment by ChristophWurst** [comment]
> check the table definition? What am I looking for?

`describe oc_twofactor_admin_codes` on mysql and mariadb

**Comment by eggithub** [comment]
This what you need?

```
+---------+---------------------+------+-----+---------+-------+
| Field   | Type                | Null | Key | Default | Extra |
+---------+---------------------+------+-----+---------+-------+
| id      | bigint(20) unsigned | NO   | PRI | NULL    |       |
| user_id | varchar(64)         | NO   | PRI | NULL    |       |
| code    | varchar(6)          | NO   |     | NULL    |       |
| expires | bigint(20) unsigned | NO   |     | NULL    |       |
+---------+---------------------+------+-----+---------+-------+
```

**Comment by ChristophWurst** [comment]
yeah, so the auto increment is missing for some reason. that explains the error.

**Comment by eggithub** [comment]
Is this the correct query then?

```
ALTER TABLE oc_twofactor_admin_codes MODIFY id BIGINT UNSIGNED AUTO_INCREMENT;
```
I'm sorry, its just once in 2 years I have to use this. Should I give some command to save this... cant remember.

**Comment by mejo-** [comment]
I think that you could close this issue as well. The original author fixed it for themself.

My best guess would be that this was about a broken upgrade with missing migration steps :woman_shrugging:
