### ISSUE TITLE
Two Factor Admin - can code generation be done via regular interface as well as cmdline

### ISSUE THREAD

**Issue by Daksol** [ChristophWurst/twofactor_admin#117]
Clarification question on Admin documentation
https://nextcloud-twofactor-admin.readthedocs.io/en/latest/Admin%20Documentation/

If the Two Factor Admin app is installed, is the option to reset a user available to an admin user (eg a user who is a member of the Admin group) via the regular web interface?

Or is the Two Factor Admin capability only usable via the commandline?
Thanks

**Comment by ChristophWurst** [comment]
You also do it via web

**Comment by Daksol** [comment]
Thanks very much. Sorry to put same thing in twice, but I think you responded so quickly the first time that I assumed I had not saved properly.

best regards
