### ISSUE TITLE
"Ask questions or discuss" option from app store does not work

### ISSUE THREAD

**Issue by Daksol** [ChristophWurst/twofactor_admin#118]
Hi
When looking at Two Factor Admin, I came to this page in the NextCloud appstore
https://apps.nextcloud.com/apps/twofactor_admin

There are various links at bottom of the page including one 
Label: Ask questions or discuss
Link: https://help.nextcloud.com/c/apps/twofactor-admin

However if you take that link you get an error message:-
Oops! That page doesn’t exist or is private.

(So someone with a question, like me, ends up using this Issues channel for questions).

**Comment by mejo-** [comment]
This issue is already fixed and can be closed.
