### ISSUE TITLE
 dependencies are not fulfilled

### ISSUE THREAD

**Issue by baer-ing** [ChristophWurst/twofactor_admin#127]
Hi

I get this error on install:
`App "Two-Factor Admin Support" cannot be installed because the following dependencies are not fulfilled: Following databases are supported: sqlite, mysql`
However I have installed mysql-server via apt. I could not find any more details about the installation for this App. Do I somewhere enter mysql details in a config file? Do I have to create a Database for it?

**Comment by ChristophWurst** [comment]
What's your version of mysql/mariadb? https://github.com/ChristophWurst/twofactor_admin/blob/41fe10123d2c5a9b67f6759604fca299095800ac/appinfo/info.xml#L25 there is a version constraint

**Comment by baer-ing** [comment]
HI ChristophWurst

Thanks for your reply. I just checked it and it shows:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.30-0ubuntu0.18.04.1 (Ubuntu)

**Comment by ChristophWurst** [comment]
Hey,

this is strange. Have you [checked the forums](https://help.nextcloud.com/search?q=%22following%20dependencies%20are%20not%20fulfilled%22)?

I don't currently have time to look into this, sorry.

**Comment by mejo-** [comment]
I would suggest to close this issue after more than one year of no response. Impossible to debug/fix without more information.
