### ISSUE TITLE
Generate tokens in web interface

### ISSUE THREAD

**Issue by MrMcX** [ChristophWurst/twofactor_admin#16]
Is there a simple way to implement the generation of tokens in the web interface? IMHO it's easier for an admin to use this interface than using the command line interface.
Thank you,
Simon

**Comment by ChristophWurst** [comment]
Hey, @MrMcX!

this should be fairly simple to implement. Would you be interested in such a contribution? I could guide you and give some help if needed :v:

**Comment by MrMcX** [comment]
If you tell me where to start, I'm indeed in implementing this.
Thank you
