### ISSUE TITLE
won't work on 20.0.6.1

### ISSUE THREAD

**Issue by Devineavenger** [ChristophWurst/twofactor_admin#173]
Updated from 20.0.4 and now it won't show up in the gui, and using occ gives a database error.

An exception occurred while executing 'SELECT COUNT(*) FROM `oc_twofactor_a    dmin_codes` WHERE `user_id` = ?' with params ["xxxxxxx":                  ]                                                                                 SQLSTATE[42S02: Base table or view not found: 1146 Table 'nextcloud.oc_two  ]  factor_admin_codes' doesn't exist                                                                                                                           In PDOStatement.php line 129:                                                                                 SQLSTATE[42S02: Base table or view not found: 1146 Table 'nextcloud.oc_two  ]  factor_admin_codes' doesn't exist                                                                                                                           In PDOStatement.php line 127:                                                                                 SQLSTATE[42S02: Base table or view not found: 1146 Table 'nextcloud.oc_two  ]  factor_admin_codes' doesn't exist

**Comment by ChristophWurst** [comment]
You could check oc_migrations for the migrations that have been run

I don't have the time to troubleshoot this right now, sorry

**Comment by Devineavenger** [comment]
ok. hope you will at one point... I don't understand why nextcloud would not have something like this implemented natively :))

this is what I found:
'twofactor_admin', '0Date20180907071626'
'twofactor_admin', '1Date20180907092152'
'twofactor_admin', '2Date20180926053333'
'twofactor_admin', '2Date20180926055748'
'twofactor_admin', '3Date20200821134736'
'twofactor_admin', '3Date20200821134738'

but I don't exactly know what to do with this information :)

As something i have noticed, no other app has a date of 2021

**Comment by ChristophWurst** [comment]
compare it to the migrations at https://github.com/ChristophWurst/twofactor_admin/tree/master/lib/Migration

there should be one that creates the table the your setup doesn't have

**Comment by Devineavenger** [comment]
Thank you. Will go through them later tonight and come back with possible results tomorrow.

**Comment by Devineavenger** [comment]
OK. At first nothing made sense... Everything was where it should be. After I uninstalled the app and manually removed the entries from the db, I did a new install... And the install did not apply the last 2 migrations... the "3Date" ones... What now? :))

**Comment by andyxheli** [comment]
@Devineavenger are you still having issues with this?

**Comment by Devineavenger** [comment]
> @Devineavenger are you still having issues with this?

Hello, no longer on that version. As I recall, I solved it by manually applying the last 2 migrations...

**Comment by andyxheli** [comment]
Awesome! If resolved? can you please close the issue ?
