### ISSUE TITLE
Nextcloud 21

### ISSUE THREAD

**Issue by sunjam** [ChristophWurst/twofactor_admin#176]
Please add support.  Thanks!

**Comment by resoli** [comment]
Hello, any new on this?

**Comment by ChristophWurst** [comment]
no

**Comment by resoli** [comment]
I see this issue is tagged "help wanted". I'm not a php developer, but if you want to assign me some task, I can try.

**Comment by ChristophWurst** [comment]
This mostly requires coding skills to understand the necessary changes and most of this app is php. https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#upgrading-to-nextcloud-21 has most of the details regarding upgrade.

**Comment by resoli** [comment]
I have coding skill, even not php specific. I will giv a try, thanks.

**Comment by robo81** [comment]
Hi, 
This was very useful app so please add support for NC21 👍

**Comment by ChristophWurst** [comment]
> please add support for NC21

This is a community app. Feel free to bring it up to standards :v:

**Comment by andyxheli** [comment]
Running NC 21.0.2 on PHP 7.4 

I  enabled this app to see if its working. So anyone that might want to use it I think you can but of course at your own risk.

**Comment by nursoda** [comment]
I had major issues on 21.0.2/PHP8, so I removed it from all instances for the time being. I didn't need to use it anyway, my users seem to be able to use backup codes or multiple 2FA settings like eMail and SMS.

**Comment by pm-pm** [comment]
Hello,
i understood, that there are a lot of changes in NC21 when using PHP8. But what about using NC21 with PHP7.4?
Because PHP7 is still supported in NC 21 why does this Application don´t work in NC21 with PHP7?
I have read the documents, but i do not found the answer or i did not understood the documents.
Can someone please explain this.
Thanks.

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#doctrine-dbal is the critical part. It doesn't matter what version of php use use. The code has breaking changes.

**Comment by 31337-4554551n** [comment]
I just wanted to say thank you for all your hard work.
This is the last app holding me back from upgrading, but looking at it's state I may have to disable it and move forward without it. Thank you as well for publishing the latest gateway app, that was the real barrier for me.
I'm not a developer either, but if there's anything I can do to help please let me know.

**Comment by 31337-4554551n** [comment]
Hey,

I'm sorry I don't really understand app development, but it looks like you've upped the tag which says it's supported for later versions, but it's not reflected in the NC app store. It still says it's not supported

**Comment by ChristophWurst** [comment]
The app wasn't released.

**Comment by 31337-4554551n** [comment]
As in it's not ready for release because it doesn't work with newer versions? Then why is the issue closed?
I'm sorry, not a dev, I don't fully understand

**Comment by ChristophWurst** [comment]
This is a bug tracker. The code issue with the compatibility is resolved. The organizational aspect of doing the release is still todo.

I don't have time to do this the next few days, you have to be patient or someone else has to help.
