### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by sunjam** [ChristophWurst/twofactor_admin#177]
Related to #176 php8 was introduced in v21.  7.x will continue to be supported for now.  Thanks

**Comment by pm-pm** [comment]
One question:
Because PHP7 is still supported in NC 21 why does this Application does not work in NC21?
All the changes are only NECESSARY when PHP 7 is not supported anymore? Am i right?

**Comment by ChristophWurst** [comment]
See https://github.com/ChristophWurst/twofactor_admin/issues/176#issuecomment-826534781. It has all the details linked.
