### ISSUE TITLE
2FA Codes seldomly works

### ISSUE THREAD

**Issue by kungenandersson** [ChristophWurst/twofactor_admin#39]
Hello,

We have been using this solution a lot in order to enforce 2FA. But almost 50% of the times (mostly when we create new accounts) the one-time code doesnt work. The error that gets returned reads as follows:

“Error while validating your second factor”

I have been creating new test accounts and immediately logged into them to find its working, but it's not working for other users sometimes. (When they report, I log in with their account and use the code I gave them, and it doesn't work until I make a new one)

Please have a look at this.

**Comment by ChristophWurst** [comment]
Yes, this app generates *one-time* codes. By using the codes you invalidate them. Just pass the codes to your users without testing them.

**Comment by kungenandersson** [comment]
Hello,

That is what I do. I give them the code immediately. Like I said, **WHEN** they report the issue, I use their code to make sure they didn't do something wrong on their end. Please re-open.

**Comment by ChristophWurst** [comment]
Okay. We need https://github.com/ChristophWurst/twofactor_admin/blob/83f9a975d639ac7b914153c25183c70b2617cfe3/lib/Service/CodeStorage.php#L86 and https://github.com/ChristophWurst/twofactor_admin/blob/83f9a975d639ac7b914153c25183c70b2617cfe3/lib/Service/CodeStorage.php#L94 to debug this.

**Comment by ChristophWurst** [comment]
Just let me know if you are a developer, then I can guide you through this. It should be a simple task to add the logging.

**Comment by kungenandersson** [comment]
Hello,

Thanks for the replies. I am not a developer

**Comment by kungenandersson** [comment]
I forgot to mention. From all the testing and cases we have seen, I believe it's related to the time for which the code is valid. Can you take a quick peek at that part of the app configuration?

**Comment by ChristophWurst** [comment]
https://github.com/ChristophWurst/twofactor_admin/blob/83f9a975d639ac7b914153c25183c70b2617cfe3/lib/Service/CodeStorage.php#L39 is the TTL. It's used when the code is generated https://github.com/ChristophWurst/twofactor_admin/blob/83f9a975d639ac7b914153c25183c70b2617cfe3/lib/Service/CodeStorage.php#L69 and checked when the code is used https://github.com/ChristophWurst/twofactor_admin/blob/83f9a975d639ac7b914153c25183c70b2617cfe3/lib/Service/CodeStorage.php#L99.

You could inspect the database to find out if a code has been used by the user and/or if it expired already. It's a unix timestamp. You can decode them like this: https://duckduckgo.com/?q=1559113607+timestamp

**Comment by kungenandersson** [comment]
Hello,

Still looking for help here.

So I can confirm that when these codes does not work, they haven't necessarily been used.
If someone can help me pull out any logs for the issue I would be grateful. I do not recall having this issue prior to upgrading to 16.01

**Comment by ChristophWurst** [comment]
> You could inspect the database to find out if a code has been used by the user and/or if it expired already. It's a unix timestamp. You can decode them like this: https://duckduckgo.com/?q=1559113607+timestamp

:point_up:

**Comment by kungenandersson** [comment]
@ChristophWurst 

While not been able to solve this issue, I found the app that enables users to get their 2FA codes by email. I see that it is outdated (not updated since nc14)

Is the app safe to use, considering it's outdated? Is there any possibilities of it getting updated? It would be a practical app.

**Comment by kungenandersson** [comment]
> > You could inspect the database to find out if a code has been used by the user and/or if it expired already. It's a unix timestamp. You can decode them like this: https://duckduckgo.com/?q=1559113607+timestamp
> 
> ☝️

So I checked the database as you suggested. I made an admin code for my account that should last 3600 * 72. I found the code and unix timestamp in the database table and it confirmed the code would expire 13th of Juni. Now first thing in the morning I checked the tables and there are no entries even though I haven't used the code. 

So the code expires before the 72 hours assigned, and before I use it. Got anything else I can try @ChristophWurst

**Comment by ChristophWurst** [comment]
Thanks for checking. Those are some interesting findings.

> So the code expires before the 72 hours assigned, and before I use it.

That part I don't get. The only code path where we delete a code is when it's actually used and matches the one from the DB: https://github.com/ChristophWurst/twofactor_admin/blob/6175777f57da5a96718f58684b5ba7502bfcea7d/lib/Service/CodeStorage.php#L95.

are you 100% sure the code is not used by someone else? :see_no_evil:

**Comment by kungenandersson** [comment]
Hello @ChristophWurst 

Yes I am positive that I have not logged in. I've created loads of test accounts for the purpose of testing. (lol) And this also affects nearly every user that we have created / given codes to. I have also studied the logs, that shows no login attempts using my or my test accounts credentials.

**Comment by kungenandersson** [comment]
@ChristophWurst  Do you think we can alter the code to make it expire only after a certain amount of time, regardless of how many times it has been used? Maybe we can use this as a means of troubleshooting the issue.

**Comment by ChristophWurst** [comment]
Just add ```\OC::$server->getLogger()->warning("deleting code $code from user " . $user->getUID())``` above https://github.com/ChristophWurst/twofactor_admin/blob/6175777f57da5a96718f58684b5ba7502bfcea7d/lib/Service/CodeStorage.php#L95 and see if/when that line is triggered.

**Comment by kungenandersson** [comment]
Thanks, I did.

What exactly does that line of code do? What should I look out for?

**Comment by ChristophWurst** [comment]
oh it's missing an `;` at the end of the line, sorry.

You'll get an entry to nextcloud.log once a code is deleted.

**Comment by kungenandersson** [comment]
Hello @ChristophWurst 

I know a user have used their code and succesfully logged in, and like you said it would, it showed up in the logs. However I generated a code for myself yesterday that I didn't use. It was showing as active in the database when I logged off yesterday, today it's gone and not use able, though there is no entry in the nextcloud.log

**Comment by ChristophWurst** [comment]
This is quite unexpected. Could you check your database logs? Is there any chance it's losing some data while persisting tables? I really don't see how the could would be deleted by Nextcloud. There is nothing like a background job for cleanup. Codes are only deleted when used successfully. Otherwise they just remain in the DB.

**Comment by kungenandersson** [comment]
Hey Christoph,

What kind of logs are we talking about? Are they found in the database, and in which table if that is the case? I checked the background jobs tables but it didn't mention anything about twofactor admin codes. Running the backgroud job manually doesn't affect the codes I just generated either.

I had an issue where the cron job would mess with the keep_session_alive, but that was fixed with the 16 patch. Do you think this may be the case here as well? (even though I can't find anything that indicate the background jobs actually affected the twofactor_admin)

Backgroud jobs are done with cron.

**Comment by ChristophWurst** [comment]
No, I'm talking about the logs of your database, so mysql or postgres logs if you're using those.

**Comment by kungenandersson** [comment]
The logs for the database show nothing either. I use MariaDB / Mysql

**Comment by kungenandersson** [comment]
I believe we have a database version older than what is required. I'll be doing an upgrade this week and I will return with results.

**Comment by kungenandersson** [comment]
@ChristophWurst 

I generated two codes. One for me and one for my colleague. When he used his, mine expired too.

**Comment by ChristophWurst** [comment]
That should not happen. We actually delete by ID. Could you enable query log, reproduce and post the actual queries here?

**Comment by kungenandersson** [comment]
@ChristophWurst 

The log says something interesting (I think?)
148151 Query    DELETE FROM `oc_twofactor_admin_codes` WHERE `id` = '0'

But if you list all codes in the Database that are active, you will see that all have the same ID, which is 0

![image](https://user-images.githubusercontent.com/50327033/60323041-450fb900-9981-11e9-88df-804c36727f83.png)

**Comment by ChristophWurst** [comment]
Weird. Have you changed the schema manually? The migrations should **not** lead to this table definition. They explicitly make the `id` and `user_id` columns primary, where the `id` is auto incremented. Are you on the latest version?

**Comment by kungenandersson** [comment]
I have done no such thing. I have not messed with this anything at all until it stopped working. Yes I am on the latest version of the app, published 3 days ago.

**Comment by kungenandersson** [comment]
Hello @ChristophWurst 

We have updated the database version now, but to the latest available, which is: 10.3.16. Would it be possible for you to add support for this version?

**Comment by ChristophWurst** [comment]
You could try setting up a new instance on another server and see if this always happen with that db version. And/or compare the migration steps at https://github.com/ChristophWurst/twofactor_admin/tree/master/lib/Migration with the final state in your database – is there anything obviously wrong?

So far you're the only person running into this and reporting it here, so I'm not sure if it's a problem with a specific instance or one in general.

**Comment by kungenandersson** [comment]
Hello @ChristophWurst 

On a fresh installation , every code generated gets a unique id in the database which it did not on the real machine. DB version is the same as on the real machine

**Comment by kungenandersson** [comment]
Update: I solved the issue.

The problem was indeed auto-increment. I ultimately solved it by running this command in mysql:

alter table oc_twofactor_admin_codes modify column id int(1) NOT NULL AUTO_INCREMENT FIRST
