### ISSUE TITLE
Admin Code Option being shown upon login despite there not being a code

### ISSUE THREAD

**Issue by HigH-HawK** [ChristophWurst/twofactor_admin#67]
Hi @ChristophWurst 

I tested the new version (0.4.1) yesterday by creating a one-time code via the web interface. The code generated fine and I could use this code to login as well.

Now when I try to login, it still gives me the option, to use a admin generated one-time code, despite there not being a code in the database. The table `oc_twofactor_admin_codes` is empty.

**Reproduction steps:**

I have three users; `admin`, `user1` and `user2`

I logged in with the `admin` user to generate a one-time code for `user1` - Now I used another browser to login with `user1` and chose `admin one-time code` option and could login fine.

Now when I try to login with `user1` it still comes up with the `admin one-time code` option whereas `user2` doesn't have that option.

It looks like something got stuck somewhere for `user1` and now it always offers that user to use a `admin one-time code` despite there is none.

What could this be?

**Screenshot:**

`user1`
![user1_admin_code](https://user-images.githubusercontent.com/33863449/64178726-4d451280-ce62-11e9-8ff7-24747f1f8be1.png)

`user2`
<img width="415" alt="user2_no_admin_code" src="https://user-images.githubusercontent.com/33863449/64178800-6221a600-ce62-11e9-9acb-5f36e005ccf0.png">

**Comment by ChristophWurst** [comment]
Please share the output of ``php occ twofactorauth:state user1`` and ``php occ twofactorauth:state user2``. Is there anything in your nextcloud.log related to this problem?

**Comment by HigH-HawK** [comment]
Morning Christoph,

I didn't know about that command, thanks for sharing this. Here is the output of that command:

**User1**

```
Two-factor authentication is enabled for user user1

Enabled providers:
- admin
- backup_codes
- totp
```

**User2**

```
Two-factor authentication is enabled for user user2

Enabled providers:
- backup_codes
- totp
Disabled providers:
- admin
```

The `nextcloud.log` unfortunately doesn't show any errors, warnings or hints towards this issue.

**Comment by ChristophWurst** [comment]
> If I look into the table `oc_twofactor_providers` in the database, it seems that the one-time code generation set the `enabled` column to 1 and didn't change it back to 0 after the one-time code had been used.
> 
> I would go ahead and change it manually as I want to see, what happens if I generate a one-time code and it expires. I'll get back to you on that one

Yep, that table is exactly why I wanted you to run these commands :)

Usually the app should clear/update that state once the code has been used. If it doesn't, you've found a bug :)

**Comment by HigH-HawK** [comment]
> Usually the app should clear/update that state once the code has been used. If it doesn't, you've found a bug :)

Yeah! No just kidding :)

I'm happy to report stuff when I see something is wrong as this helps to improve it :+1: And you are doing a great job fixing these, as the updates come quite regularly, which is very good 👍

**Comment by ChristophWurst** [comment]
When the code matches we

* Fire off an event https://github.com/ChristophWurst/twofactor_admin/blob/2e38dec63dd78933b22b819c8482498f8066b8a6/lib/Service/CodeStorage.php#L97
* Which is handled https://github.com/ChristophWurst/twofactor_admin/blob/43e0038749a1f6970a9ba2dbc28cb1d86ac3e26a/lib/AppInfo/Application.php#L41
* And disables the provider for that user https://github.com/ChristophWurst/twofactor_admin/blob/6952db2a4d49f1da47d1aac2a60bb9c2e8278d03/lib/Listener/StateChangeRegistryUpdater.php#L50

Was this a one-time error or can you still reproduce?

**Comment by HigH-HawK** [comment]
Really strange, I don't seem to be able to reproduce this issue anymore 🤔 

I generate the code as usual and use that code to login with the user (checked the database as well if the code exists and if the provider is set to 1) After the login with the one-time code I logged back out and tried logging in again and this time it was ok but I haven't changed anything 🤔

**Comment by ChristophWurst** [comment]
That's strange, indeed.

Let's close this ticket then. If you ever find yourself in the situation with the wrong state please immediately check your nextcloud.log. A bug could prevent the state change. Other than that I do not have an explanation for this :man_shrugging:
