### ISSUE TITLE
Login with admin code not possible

### ISSUE THREAD

**Issue by MTBfs** [ChristophWurst/twofactor_admin#84]
Hello,

I generated an one-time-admin-code, but when i want to login with this code, there is no chance to use it. I can only use TOTP (Authenticator app) and backup-codes, but only when backup-codes were generated.
In oc_twofactor_providers there is activated admin, totp and for some useres also backup_codes. And in oc_twofactor_admin_code I can find the generated code for this user.
I can reproduce this problem with diffrent users.

What could this be?
Thank you.

**Comment by ChristophWurst** [comment]
Hi,

thanks for the detailed report.

> In oc_twofactor_providers there is activated admin, totp and for some useres also backup_codes. And in oc_twofactor_admin_code I can find the generated code for this user.

This seems fine. What version of Nextcloud do you use?

**Comment by MTBfs** [comment]
Hi,

Thanks for the answer. At the moment I use version 16.0.5.
There is an update to 17.0.1 available, but I haven't time at the moment to check on another system if this version runs without errors. So I didn't do the update yet.
Thank you.

**Comment by MTBfs** [comment]
Hi,

I updated today to version 16.0.6. And I've the same problems with the admin-codes.
I wanted also to update on 17.0.1, but this update is not running right, after I tried this update, I couldn't use nextcloud anymore.
So I'm useing at the moment version 16.0.6 and I try the update to nextcloud 17, when I've more time.
Thank you.

**Comment by ChristophWurst** [comment]
Hi,

did you update to 17 in the meantime?

I just released https://github.com/ChristophWurst/twofactor_admin/releases/tag/v2.0.0 and it might fix an edge case with the provider state.

**Comment by MTBfs** [comment]
Hi,

sorry, I was in holiday.
I wanted to do the update on 17.0.2, but I'm getting every time a white screen without any html-code.
For the moment I'm staying with version 16.0.6. Maybe in two weeks I've more time then I'll work on the problem with the update. After that, I'll check if the problem with the admin-code is gone.

Thank you for the moment. I'll inform you when I've fixed the update problem.

**Comment by MTBfs** [comment]
Hi,

now I had the time to update on 17.0.3. And I'm also using version 2.0.0 of Two-Factor Admin Support. But when I activate admin code for a user, I get an message, that no method for TOTP could be loaded. In this window I get all methods except the one for admin codes (see attached screenshot).
Do you have any ideas?
Thank you.

<img width="322" alt="TOTP-admin" src="https://user-images.githubusercontent.com/58032674/75148597-4e177c80-5700-11ea-9524-5ade207942be.png">

**Comment by MTBfs** [comment]
Hi,

I've found this in the log files:
[core] Error: two-factor auth provider 'admin' failed to load
Do you have any idea what the problem might be?

**Comment by ChristophWurst** [comment]
is the app still enabled?

**Comment by ChristophWurst** [comment]
check your nextcloud.log

**Comment by MTBfs** [comment]
Hi there,

many thanks for your help. The app works fine for me now.
After a new installation of Two-Factor Admin Support the problem could be solved. Hopefully it will still work after an update to Nextcloud 18.
Thanks again.
